languageCode: 'fr'
title: Développeur web junior à Bordeaux
theme: 'simple-onepage-and-gallery'
baseURL: https://arthaudproust.fr
removePathAccents: true

params:
  email: contact@arthaudproust.fr
  phone: "07 83 39 28 88"
  seo:
    author: Arthaud
    title: Développeur web junior à Bordeaux
    desc: "Developpement web, photographie, étudiant au MMI Bordeaux. Je suis passionné, curieux et créatif - Arthaud Proust"
    url: https://arthaudproust.fr
    links:
      github: https://github.com/arthaud-proust
      linkedin: https://www.linkedin.com/in/arthaud-proust/
      twitter: https://twitter.com/arthaud_proust
      facebook: https://www.facebook.com/arthaudproust.fr
      instagram: https://www.instagram.com/arthaudproust/

menu:
  main:
    - name: À propos
      pre: about
      url: "/#about"
      weight: 1
     
    - name: Compétences
      pre: skills
      url: "/#skills"
      weight: 2
    - name: Réalisations
      pre: projects
      url: "/#projects"
      weight: 3
    - name: Me contacter
      pre: meet-us
      url: "/#meet-us"
      weight: 4
    
    
taxonomies:
    

related:
  includeNewer: true
  toLower: true
  indices:
    - name: techno
      weight: 1