languageCode: 'fr'
title: Arthaud Proust
baseURL: https://arthaudproust.fr
removePathAccents: true

params:
  email: proust@arthaud.dev
  phone: "07 83 39 28 88"
  seo:
    author: Arthaud Proust
    title: Arthaud Proust - Développeur web junior à Bordeaux
    desc: "Développeur de site web, front & back, photographe amateur, MMI Bordeaux. Passionné, curieux et créatif - Arthaud Proust"
    url: https://arthaudproust.fr
    hero: /sprites/hero-min.jpg
    logo: /sprites/logo.png
    links:
      github: https://github.com/arthaud-proust
      githubArchive: https://github.com/arthaud-proust-archive
      linkedin: https://www.linkedin.com/in/arthaud-proust/
      twitter: https://twitter.com/arthaud_proust
      facebook: https://www.facebook.com/arthaudproust.fr
      instagram: https://www.instagram.com/arthaudproust/      

menu:
  homepage:
    - name: À propos
      pre: about
      url: "/#about"
      weight: 1
    - name: Réalisations
      pre: projects
      url: "/#projects"
      weight: 2
    - name: Compétences
      pre: skills
      url: "/#skills"
      weight: 3
    - name: Me contacter
      pre: meet-us
      url: "/#meet-us"
      weight: 4

  main:
    - name: Galerie photo
      pre: galleries
      url: "/galleries/"
      weight: 3
    - name: Lab
      pre: lab
      url: "/lab/"
      weight: 4
    - name: Références
      pre: references
      url: "/references/"
      weight: 5
    - name: Ressources
      pre: resources
      url: "/resources/"
      weight: 6
    
taxonomies:
    

related:
  includeNewer: true
  toLower: true
  indices:
    - name: techno
      weight: 1