[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.97.0"

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

  for = "*.pdf"
    [headers.values]
    X-Robots-Tag "none"