backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/media'
public_folder: '/media'
locale: fr
slug:
  encoding: ascii
  clean_accents: true

collections:
  - name: galleries
    label: Galeries
    label_singular: Galerie
    folder: content/galleries
    create: true
    editor: { preview: false }
    filter: {field: "visibleInCms", value: true}
    fields:
      - { label: "Visible", name: "visibleInCms", widget: hidden, default: true}
      - { label: Titre, name: title }
      - { label: Description, name: description, widget: markdown, minimal: true, required: false, buttons: [bold, link], editor_components: [], modes: [rich_text] }
      - { label: "Image", name: "image", required: true, widget: "image", allow_multiple: false, choose_url: false, media_folder: /assets/images/galleries, public_folder: /images/galleries}
      - { label: "Contenu", name: images, widget: list, fields: [
          { label: "Image", name: "image", required: true, widget: "image", allow_multiple: false, choose_url: false, media_folder: /assets/images/galleries, public_folder: /images/galleries},
          { label: Titre, name: title },
          { label: Description, name: desc },
        ]}

    
  - name: projects
    label: Projects
    label_singular: Projet
    folder: content/projects
    create: true
    editor: { preview: false }
    filter: {field: "visibleInCms", value: true}
    fields:
      - { label: "Visible", name: "visibleInCms", widget: hidden, default: true}
      - { label: Brouillon, name: draft, widget: "boolean", default: false}
      - { label: Titre, name: title }
      - { label: "Poids (ordre)", name: weight, required: false, widget: number, valueType: "int" }
      - { label: "Image", name: "image", required: false, widget: "image", allow_multiple: false, choose_url: false, media_folder: /assets/images/projects, public_folder: /images/projects}
      - { label: Description, name: description, required: false, widget: markdown, minimal: true, buttons: [bold, link], editor_components: [], modes: [rich_text] }
      - { label: Technologies, name: technos, required: false, widget: relation, collection: technos, value_field: techno, search_fields: [techno], multiple: true}
      - { label: Lien projet, name: project_url, required: false }
      - { label: Lien github, name: github_url, required: false }
      - { label: "Contenu", name: content, widget: list, fields: [
          { label: Titre, name: title },
          { label: Date, name: date, required: false },
          { label: "Image", name: "image", required: false, widget: "image", allow_multiple: false, choose_url: false, media_folder: /assets/images/projects, public_folder: /images/projects},
          { label: Paragraphe 1, name: paraph1, required: false, widget: markdown, minimal: true, buttons: [bold, link], editor_components: [], modes: [rich_text] },
          { label: Paragraphe 2, name: paraph2, required: false, widget: markdown, minimal: true, buttons: [bold, link], editor_components: [], modes: [rich_text] }
        ]}
    
  - name: technos
    label: Technologies
    label_singular: Technologie
    folder: content/technos
    create: true
    editor: { preview: false }
    filter: {field: "visibleInCms", value: true}
    fields:
      - { label: "Visible", name: "visibleInCms", widget: hidden, default: true}
      - { label: Brouillon, name: draft, widget: "boolean", default: false}
      - { label: Techno, name: techno }
      - { label: Image url, name: img }

  - name: content
    label: Contenu
    editor: { preview: false }
    files: 
      - name: references
        label: Références
        file: content/references/_index.md
        fields:
          - { label: Titre, name: title }
          - { label: Description, name: description, widget: "text" }
          - { label: Livres, name: books, widget: list, fields: [
              { label: Titre, name: title },
              { label: "Auteur(s)", name: author, widget: list, fields: [
                  { label: Nom, name: name },
                  { label: Lien, name: link, required: false },
              ]},
              { label: "Image", name: "image", widget: "image", allow_multiple: false, choose_url: false, media_folder: /assets/images/references, public_folder: /images/references}
            ]}
      - name: resources
        label: Resources
        file: content/resources/_index.md
        fields:
          - { label: Titre, name: title }
          - { label: Description, name: description, widget: "text" }
          - { label: Catégories, name: categories, widget: list, fields: [
              { label: Titre, name: title },
              { label: Sous-titre, name: subtitle },
              { label: "Liens", name: links, widget: list, fields: [
                  { label: Texte, name: text },
                  { label: Lien, name: link },
              ]}
            ]}
          
